<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>defaultWS</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>24a6a08e-8035-4f43-834e-44c95dcc8c1c</testSuiteGuid>
   <testCaseLink>
      <guid>bfe07bff-24ec-413f-95e3-a51c99c20d6c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/LoginCID008</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>b2bd92ad-0ae8-4e04-bacd-fcedb5740c59</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/logindata</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>b2bd92ad-0ae8-4e04-bacd-fcedb5740c59</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>url</value>
         <variableId>fe03db76-0b84-4b7a-8094-54ee1ab463d2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>b2bd92ad-0ae8-4e04-bacd-fcedb5740c59</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>userName</value>
         <variableId>416338ed-00a8-4bde-917d-705973e9b382</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>b2bd92ad-0ae8-4e04-bacd-fcedb5740c59</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>pwd</value>
         <variableId>0b0baacf-91bc-4212-8e40-8910402c0006</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2b52c32d-5708-4e71-b5b4-4110feefe964</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/makedefaultWS</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>85253482-a417-4801-9e74-7fdb84632d1a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f0b10eae-73f1-4360-afed-88bacf0f0a2f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>84a309df-239b-4334-a5c5-ae9c16ae01a4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cbbe9797-137d-4716-9857-c15d60d79988</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>88cfa382-8c0f-482d-82eb-111439b3d6aa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>71242149-810d-49db-8643-ed105bc0275b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3cac7ee8-54e2-42bb-950b-83cc527842db</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>118487c6-bcbf-41c4-beac-0553bf181a38</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1e21c21d-85be-41ef-9cd6-47e15882f85f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b63dac71-cda4-40b8-9983-300267a0ba6d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9e4eb73e-8c2c-43f4-a166-7ef9e6191208</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>562a4f6b-4fc9-46f0-8835-12b6b23971a0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6b464751-5d9e-42d0-b9ca-fb88b30baa95</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>04da12b7-cc75-45b3-a74b-3130643d9696</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>71925266-45e2-46c3-a1ae-2a0507306319</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ccacc7f2-32fd-4204-8ad4-e02d02b04bae</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>168ab876-82ce-4e4c-989e-e80d54845964</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f9d6969c-fc8b-4cf7-8a5a-3080adb00bea</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d2484a03-e04a-430d-a0c1-6fb869cf781c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e22aff63-53b3-43a9-83e4-a420876ccf7f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>62ad917d-bb64-4556-a05c-7437d8d401d2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>340b7d29-503a-4510-ac74-cf6e8e7298c9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>24632ac8-9468-40ed-85ef-07b492389699</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dadbd714-9d83-427c-8c6e-286d8b39aa4d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3d8d2b5b-9c7a-40d7-9016-31f23411483d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4fdfcf57-cecc-4288-9cf1-79afdb5cfb2b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4e8f3445-bec0-423e-b596-909b970abfdc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6f5fe26c-5ba4-4b94-93f9-4973c0abd2ad</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>525ff0e8-b9ca-4294-9962-7a5c1afcc53b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6a2e258b-b95e-4675-b651-39e70766b8f1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>50e228a4-c258-4e94-8383-d0f3c6e1a523</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8c20b1dd-8fd1-4588-ba0f-bb0a29c18961</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>154c5de1-c25b-46c0-a7aa-4c97e31508cf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2202626a-81b6-4ad1-9b03-06108c36ea81</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d0d37f59-70a0-49e5-9898-e2e3a36b4dfd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c93b3090-8173-4feb-a955-cb1419227449</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4b416c23-0fea-4333-bfb6-c3371f68537b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0a9ed743-07ef-4a9d-a682-16bc19ce16f7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>81733c2e-a089-48d4-bda3-27a12fd32ff8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bfef3f5f-d8dc-4b2d-8467-468777a751ce</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c3dd242c-d4f0-41ce-9b94-964934c820c1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f91fe24d-c95d-4301-8442-c9425b7fed3c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d7dab57e-cf55-4f8d-80cd-46f1de317b24</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7fdb5f70-93cb-4534-a175-97112dd6ed15</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>adeff4fa-6ba7-4f67-9c90-96ebe0f1dae9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8b7e37a0-8c98-43d1-8317-8e69f7dfd70e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8bd18471-7323-46e4-a4ab-a6952279cb98</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e95ca312-41fd-4dcb-a97d-8b6e3ca9bed8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8a2f8887-790b-41eb-8b7c-41db28cf9ff8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6b906dd6-e600-4feb-8b44-9624ff57a565</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0122a5c7-f191-4370-8d08-356f10f7270a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aac834ae-29cb-4bf4-8313-df24350d05f8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4b3fa6ee-591c-41c3-b85a-cd274997d3ce</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a19272d4-da07-4f65-bafa-4b9b58071840</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1f2b87bd-a01c-49ed-9c6c-4f655fbd330f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>53288683-98a0-490d-b64f-741ffb95a096</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>260dae1c-74a5-4c33-aa14-581fd6b88391</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d369214d-81c8-4169-9e80-17bd0e20a801</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ec6a8f6d-c1bc-4faf-abfb-edb47e8cbd24</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>11694e9f-314d-4581-b8d5-b8c7bdf96e3f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8e536ae0-1e75-46a8-8539-ecd543c87b39</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f526ed83-e1fa-4097-a673-b2be37ee2d5b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1a0eef2e-0c3c-452a-8414-20cb1cd7be4c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d935c3eb-da9c-4f68-8c3e-c2cc6899980f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cf72ff69-435e-40f2-8ce4-5f24d74aa564</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
