<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>grphist</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>d7aa992f-1b1e-4d60-887a-cf0478d23515</testSuiteGuid>
   <testCaseLink>
      <guid>0ef1931b-66b7-4f0d-9421-f79750ee10ac</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/LoginCID008</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>b465dd7a-d15c-4fb1-a58a-4b1f47399cee</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/logindata</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>b465dd7a-d15c-4fb1-a58a-4b1f47399cee</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>url</value>
         <variableId>fe03db76-0b84-4b7a-8094-54ee1ab463d2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>b465dd7a-d15c-4fb1-a58a-4b1f47399cee</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>userName</value>
         <variableId>416338ed-00a8-4bde-917d-705973e9b382</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>b465dd7a-d15c-4fb1-a58a-4b1f47399cee</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>pwd</value>
         <variableId>0b0baacf-91bc-4212-8e40-8910402c0006</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bb3c5363-64d4-4be2-b70b-d0b39be8fa40</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/histFilts</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>02032c2b-2cf0-4cfb-9fcb-09db34938dd5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f9016083-f502-4226-a650-8e064f8a292a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>81782b5c-eeed-421d-bb9e-699a2d28f1c0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>994e98ec-4365-4831-83bf-0a255b1730ad</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>996ad08d-29ae-4acf-a189-16f3bdf912d6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9da09d1c-f7af-4575-a7d0-c59baf0e8ab4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1c1db44b-0a8a-4418-aa55-d39d0d96f63d</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
