<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>test2prodkatalon</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>9b7c0a83-df44-4533-a110-9e84a0554eb9</testSuiteGuid>
   <testCaseLink>
      <guid>9c3cf1e8-9281-426b-b492-25059798b88a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/LoginCID008</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>d1d4ae96-fb97-42a8-8e6c-7116385e95d3</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/test2prod</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>d1d4ae96-fb97-42a8-8e6c-7116385e95d3</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>url</value>
         <variableId>fe03db76-0b84-4b7a-8094-54ee1ab463d2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>d1d4ae96-fb97-42a8-8e6c-7116385e95d3</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>userName</value>
         <variableId>416338ed-00a8-4bde-917d-705973e9b382</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>d1d4ae96-fb97-42a8-8e6c-7116385e95d3</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>pwd</value>
         <variableId>0b0baacf-91bc-4212-8e40-8910402c0006</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7e17129a-6cd3-4e61-8d1c-4e2a6b4fe764</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/FltattrOriginalNM</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a1d7f917-31d0-423f-92fc-26aed8b0f446</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2745de60-b791-403a-956e-6f06b59e1fed</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dfea374a-b25c-4bae-b791-ce2a358e0c0c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>10b5e42f-874e-44f7-9182-21e2c7e09cb6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>93905d44-e264-4b27-a3ae-181e5fa589e3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>13a90c9c-e95e-490e-936c-44d88406d8db</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9a76f885-72bf-4460-a96b-0b90f3905fe9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0c91f4c8-084d-443c-ab97-c3a0ec345364</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c9a2b4b1-5e4e-4a17-bf42-463bec8a8516</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8c5dd149-18b5-4139-b003-e942eae6d5ac</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>73a393e3-21ab-49d2-b7ab-230ec0767d17</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d4c1217e-d957-4406-a938-0443aefd231e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c6b3630b-0fff-48d5-b011-59ed1e4816a9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>764d72d8-09f5-410d-a298-f2101f6a7476</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>48376880-85f6-4398-9f2f-e939d1867271</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>92f380ad-5751-46f5-8435-6ab3b3e68c22</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>77eb87eb-62ae-4688-9ee8-9a9d4d9d7788</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>461c235b-e8ad-4cba-9608-7c9c812a31b1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>087e5e98-90d4-4127-8f12-6bbd77490530</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>540d9191-c0c2-47c3-b8a2-93b6b546d66e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>07bd3586-d242-4b77-a1b7-bfb3a2afc5ac</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b2433e8e-7fdf-4dda-be9a-e8f8b1a551e2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a91af551-d52a-439a-b910-d781a4fbf313</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>11dd3716-aeb3-43e0-b32a-7e69eac66ba6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>28d0f50d-cc34-4ec3-99ef-fba2c5f1445f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>50bf1f02-0e0b-4402-af64-38270e9f2c23</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cc8f7935-2f36-495d-a59b-a7da5136204c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e29067e1-52e8-4882-887c-5823ec33acfe</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c4f858b0-534e-44f5-8224-52da2a69f4a3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f8534d66-0992-4dc8-ad4e-4ea1e00d7162</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>14524b67-b564-45ec-9b61-ed1cf0b188ab</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0c9e808c-8e07-4d0f-bc90-28c589aa890b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6aa614dc-1ebc-4e8c-ba68-d516e34698d9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>04679730-da5f-4dd9-98a9-5f20131d7659</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>93f64337-b07e-4a36-8d8a-417d2aab7b9d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0b1f0b76-7b4f-472b-804a-d09350c80f56</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bc01a41e-323d-4a75-9467-f2624c09365f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>62a8ff12-165c-4cee-9d4d-eec413c23e6a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a6fc07dc-2961-4fb7-a4a5-c9b878ca6e4f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e167b59a-b339-4376-91f4-8a9549909d94</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a2e349c4-9812-48b4-b22e-42776f9cd286</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dc7637d0-15f8-48ce-a8dc-f7593205f9fc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a17c5e47-5748-465f-8a3d-ecb6cb777659</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>83f3348f-5b8c-42eb-8b06-2568a9ee1850</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7e37a9c4-31d8-447e-82ad-aba316793b81</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2e5cae40-9891-436d-bbb8-0bddcd9cb13d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e1c9b375-4114-478c-a595-490f812c3ce6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ebdbb487-5867-43f2-b442-c2e17e3241f2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0f77f95d-3fa9-479c-a673-23a3e3056c7c</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
